# Default configuration for alignmap value alignment

# Values to align
values:
  - "humor"
  - "gpt2-helpful" 
  - "gpt2-harmless"
  - "diversity"
  - "coherence"
  - "perplexity"

# Target palette (c values)
target_palette:
  - 0.5
  - 0.8
  - 0.3
  - 0.2
  - 0.1
  - -0.2

# Reward data settings
reward_data:
  file_path: "results/model-data.json"  # Path to rewards data file

# Optimization settings
optimization:
  learning_rate: 0.1
  max_steps: 150
  sequential: false
  rounds: 1  # For sequential optimization

# Device settings
device:
  auto_detect: true  # Automatically detect the best device
  mixed_precision: false
  memory_efficient: true

# Output settings
output:
  verbose: true
  save_results: true
  save_path: "results/alignment_results.txt" 